import type { Metadata } from 'next'
import { Manrope as FontSans } from 'next/font/google'
import Image from "next/image"
import Link from "next/link"
import { CircleDollarSign, Landmark, LayoutDashboard, Tags } from 'lucide-react'

import { cn } from "@/lib/utils"

import './styles/globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(fontSans.variable)}>
      <body className="bg-slate-100 text-gray-600">
        <div className="flex">
          <div className="shrink-0 w-56">
            <aside
              className="h-full w-56 fixed border-r bg-white border-black[0.07]"
              aria-label="Sidebar"
            >
              <div className="flex justify-center py-4 mt-4">
                <Image src="/logo.svg" width={36} height={36} className="mr-3" alt="Control Money Logo" />
                <span className="self-center text-xl font-semibold whitespace-nowrap">Control Invest</span>
              </div>
              
              <ul className="px-3 py-4 space-y-2">
                <li>
                  <Link href="/" className="flex items-center p-3 rounded-lg text-gray-500 hover:bg-slate-100">
                    <div className="flex gap-4">
                      <LayoutDashboard strokeWidth={1.5} />
                      Dashboard
                    </div>
                  </Link>
                </li>
                
                <li>
                  <Link href="/transactions" className="flex items-center p-3 rounded-lg text-gray-500 hover:bg-slate-100">
                    <div className="flex gap-4">
                      <CircleDollarSign strokeWidth={1.5} />
                      Transações
                    </div>
                  </Link>
                </li>

                <li>
                  <Link href="/categories" className="flex items-center p-3 rounded-lg text-gray-500 hover:bg-slate-100">
                    <div className="flex gap-4">
                      <Tags strokeWidth={1.5} />
                      Categorias
                    </div>
                  </Link>
                </li>

                <li>
                  <Link href="/accounts" className="flex items-center p-3 rounded-lg text-gray-500 hover:bg-slate-100">
                    <div className="flex gap-4">
                      <Landmark strokeWidth={1.5} />
                      Contas
                    </div>
                  </Link>
                </li>
              </ul>
            </aside>
          </div>
          
          <main className="p-8 w-full max-w-screen-2xl mx-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
