import { Manrope as FontSans } from 'next/font/google'

import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { CIStoreProvider } from '@/hooks/control-invest-store-provider'
import { monthsByLocale } from '@/utils/date'
import { fetchAccounts } from '@/services/account'
import { fetchCategories } from '@/services/category'
import { fetchAccountTypes } from '@/services/account-type'
import { fetchTransactionType } from '@/services/transaction-type'
import { fetchTransactions } from '@/services/transaction'

import StoreInitializer from '@/components/layout/store-initializer'
import Sidebar from '@/components/layout/sidebar'

import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function loadData() {
  const currentDate = new Date()
  const month = monthsByLocale('en')[currentDate.getMonth()].toLowerCase()
  const year = currentDate.getFullYear().toString()
  
  const transactions = await fetchTransactions({ month, year })
  const transactionTypes = await fetchTransactionType()
  const transactionType = transactionTypes.find(() => true)
  
  const categories = await fetchCategories(transactionType.id)
  const accounts = await fetchAccounts()
  const accountTypes = await fetchAccountTypes()
  
  return {
    accountTypes,
    accounts,
    categories,
    transactions,
    transactionTypes
  }
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const store = await loadData()
  
  return (
    <html lang="pt-BR" className={fontSans.variable} suppressHydrationWarning>
      <body>
        <div className="flex">
          <div className="shrink-0 w-56">
            <Sidebar />
          </div>
          
          <main className="p-8 w-full max-w-screen-2xl mx-auto">
            <CIStoreProvider>
              <StoreInitializer {...store}>
                {children}
              </StoreInitializer>
            </CIStoreProvider>
          </main>
        </div>
      </body>
    </html>
  )
}
