import { Manrope as FontSans } from 'next/font/google'

import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { request } from '@/server/request'
import { CIStoreProvider } from '@/hooks/control-invest-store-provider'

import StoreInitializer from '@/components/layout/store-initializer'
import Sidebar from '@/components/layout/sidebar'

import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function loadData() {
  const accountTypesResponse = await request('/account-type', { cache: 'no-store' })
  const accountsResponse = await request('/account', { cache: 'no-store' })
  const transactionTypesResponse = await request('/transaction-type', { cache: 'no-store' })

  const transactionTypes = await transactionTypesResponse.json()
  const transactionType = transactionTypes.find(() => true)
  
  const categoriesResponse = await request(`/category/type/${transactionType.id}`, { cache: 'no-store' })
  
  const categories = await categoriesResponse.json()
  const accounts = await accountsResponse.json()
  const accountTypes = await accountTypesResponse.json()
  
  return {
    accountTypes,
    accounts,
    categories,
    transactionTypes
  }
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const store = await loadData()
  
  return (
    <html lang="pt-BR" className={fontSans.variable} suppressHydrationWarning>
      <body>
        <div className="flex">
          <div className="shrink-0 w-56">
            <Sidebar />
          </div>
          
          <main className="p-8 w-full max-w-screen-2xl mx-auto">
            <CIStoreProvider>
              <StoreInitializer {...store}>
                {children}
              </StoreInitializer>
            </CIStoreProvider>
          </main>
        </div>
      </body>
    </html>
  )
}
